### PR TITLE
Fix compilation error under elixir 1.13

### LINKED ISSUE #42: Error compiling on elixir 1.13.1
I'm getting an error the first time I try to build the nif using the latest version of elixir. 

Last log lines are as follows
```
~/.cache/mix/installs/elixir-1.13.1-erts-12.2/febfcb37852cfa2dd1caf0e08cdda1de/deps/erlkaf/deps ~/.cache/mix/installs/elixir-1.13.1-erts-12.2/febfcb37852cfa2dd1caf0e08cdda1de/deps/erlkaf
~/.cache/mix/installs/elixir-1.13.1-erts-12.2/febfcb37852cfa2dd1caf0e08cdda1de/deps/erlkaf
make[1]: Entering directory '/root/.cache/mix/installs/elixir-1.13.1-erts-12.2/febfcb37852cfa2dd1caf0e08cdda1de/deps/erlkaf/c_src'
 CPP    erlkaf_consumer.cc
 CPP    queuemanager.cc
 CPP    topicmanager.cc
 CPP    erlkaf_nif.cc
 CPP    queuecallbacksdispatcher.cc
 CPP    erlkaf_logger.cc
 CPP    nif_utils.cc
 CPP    erlkaf_message.cc
 CPP    erlkaf_producer.cc
 CPP    erlkaf_config.cc
 LD     erlkaf_nif.so
make[1]: Leaving directory '/root/.cache/mix/installs/elixir-1.13.1-erts-12.2/febfcb37852cfa2dd1caf0e08cdda1de/deps/erlkaf/c_src'
===> Analyzing applications...
===> Compiling erlkaf
===> Missing artifact priv/erlkaf_nif.so
** (Mix.Error) Could not compile dependency :erlkaf, "/root/.mix/rebar3 bare compile --paths /root/.cache/mix/installs/elixir-1.13.1-erts-12.2/febfcb37852cfa2dd1caf0e08cdda1de/_build/dev/lib/*/ebin" command failed. Errors may have been logged above. You may run Mix.install/2 to try again or change the arguments to Mix.install/2 to try another version
```

**Steps to reproduce**

> I created a simplified flow using docker, but it is happening on my local installation as well.

 
Using the following `Dockerfile` to get latest elixir version and erlkaf build dependencies

```Dockerfile
FROM elixir:1.13.1-slim AS app_builder

RUN apt-get update && \
    apt-get install -y --no-install-recommends git build-essential libssl-dev libcrypto++-dev zlib1g-dev libsasl2-dev \
                     liblz4-dev libzstd-dev ca-certificates
```

Then just build, start the container and test the installation:

```shell
docker build -t erlkaf_test .
docker run -it --rm erlkaf_test

iex(1)> Mix.install([{:erlkaf, github: "silviucpp/erlkaf"}])

# there will be a propmt to install rebar
```

Then the error occurs, after that if you try again on the same image it installs just fine. Maybe it is related to https://github.com/elixir-lang/elixir/issues/11530

### PR DESCRIPTION
**Pull request by escobera**
fixes #42

### CODE REVIEW

**Comment by escobera** [comment]
@silviucpp this is my first time dealing with makefiles, don't know if this is enough, specially on the pure erlang side of things. Try and give it a spin before merging please. Any feedback is greatly welcome!

**Comment by silviucpp** [comment]
@escobera I tested on erlang and all it's ok. with this fix also elixir it's working ?

**Comment by escobera** [comment]
Oh noes! This isn't good enough :cry: 
Hmm, my tests are failing at CI.

```/builds/prospeccao/antecedentes/deps/erlkaf/deps /builds/prospeccao/antecedentes/deps/erlkaf
/builds/prospeccao/antecedentes/deps/erlkaf
make[1]: Entering directory '/builds/prospeccao/antecedentes/deps/erlkaf/c_src'
 CPP    erlkaf_config.cc
 CPP    erlkaf_consumer.cc
 CPP    erlkaf_logger.cc
 CPP    erlkaf_message.cc
 CPP    erlkaf_nif.cc
 CPP    erlkaf_producer.cc
 CPP    nif_utils.cc
 CPP    queuecallbacksdispatcher.cc
 CPP    queuemanager.cc
 CPP    topicmanager.cc
 LD     erlkaf_nif.so
/usr/bin/ld: cannot open output file /builds/prospeccao/antecedentes/_build/test/lib/erlkaf/priv/erlkaf_nif.so: No such file or directory
collect2: error: ld returned 1 exit status
make[1]: *** [nif.mk:78: /builds/prospeccao/antecedentes/_build/test/lib/erlkaf/priv/erlkaf_nif.so] Error 1
make[1]: Leaving directory '/builds/prospeccao/antecedentes/deps/erlkaf/c_src'
make: *** [Makefile:7: compile_nif] Error 2
===> Hook for compile failed!
```

**Comment by silviucpp** [comment]
I guess /builds/prospeccao/antecedentes/_build/test/lib/erlkaf/priv/erlkaf_nif.so does not exists. can you search where was generated instead ?

**Comment by escobera** [comment]
> I guess /builds/prospeccao/antecedentes/_build/test/lib/erlkaf/priv/erlkaf_nif.so does not exists. can you search where was generated instead ?

I'm pokin around our CI here to check what's going on. Will report once I have that info.

**Comment by escobera** [comment]
@silviucpp .so file is not generated, maybe it is a race condition of sorts?

**Comment by silviucpp** [comment]
Hmm basically `ld` reports that cannot open the location: `/usr/bin/ld: cannot open output file /builds/prospeccao/antecedentes/_build/test/lib/erlkaf/priv/`. Does this path exists ?

**Comment by escobera** [comment]
Tested on my application here and it is building correctly now! :partying_face:

**Comment by silviucpp** [comment]
Can you test by replacing with the attached file. I did some cleanups . in my opinion looks better. What I did was to insert a new var named `PRIV_DIR` and set it based on `REBAR_BARE_COMPILER_OUTPUT_DIR` .

Just to avoid setting the priv dir location into multiple places inside the make file. Please review and commit and see if it's working. on erlang works

[https://www.dropbox.com/s/fmmf306x31hfcwa/nif.mk?dl=1](url)

**Comment by escobera** [comment]
Yeah, your version definitely looks better. It works on my test case and app. Thanks for the feedback!

**Pull request merged**
