### PR TITLE
use OTP logger on OTP-21+

### PR DESCRIPTION
**Pull request by tsloughter**
As mentioned in my other PR, we have Elixir apps to use this as well.

I'd have suggested moving to logger anyway but since Elixir and OTP logger play well together and I don't think it plays well with lager I figured I'd go ahead and make this PR now.

### CODE REVIEW

**Comment by silviucpp** [comment]
Merged

**Comment by tsloughter** [comment]
Why was this reverted? https://github.com/silviucpp/erlkaf/commit/b32cab4044c9fc3a7568a2e90e653f2a6079967e

**Comment by escobera** [comment]
@silviucpp I'm having trouble with lager + elixir + phoenix here as well. Am curious as well why was this reverted.

**Comment by tsloughter** [comment]
Yea, I can work on a new PR if I knew what needed to be done different.

**Comment by silviucpp** [comment]
@escobera @tsloughter Please see this thread https://github.com/silviucpp/erlkaf/issues/11#issuecomment-482582711 . I faced some issues with this change and at that point @tsloughter told me that what I want is not supported ...

I have no idea if something changed

**Comment by silviucpp** [comment]
@tsloughter  One idea will be to just read the logging library from an env variable ?

**Comment by silviucpp** [comment]
Finally we are no longer linked to lager into our production. In the last master (publish a release soon) the library migrated to logger.

**Pull request merged**
